### ISSUE TITLE
Gnome tweak tool

### ISSUE THREAD

**Issue by mackay508** [LinxGem33/Arc-Menu#101]
I have the latest Arc Menu Gnome (13) tweak tool installed (3.25.4-0ubuntu1) but when I go to launch Tweak tools from the menu it comes up with:

Execution of "gnome-tweak-tools" failed:
Command not found.
I have uninstalled and reinstalled both Arc Menu and Gnome Tweak Tools, is there a way to fix this?

No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu Artful Aardvark (development branch)
Release:	17.10
Codename:	artful

GNOME Shell 3.24.3

length values must specify a unit
length values must specify a unit
Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2800008 (Software)
JS ERROR: TypeError: label is undefined
onAppMenuHover/tooltipDelayCallbackID<@/home/seoras/.local/share/gnome-shell/extensions/pixel-saver@deadalnix.me/app_menu.js:116:8

Source ID 261312 was not found when attempting to remove it
Attempting to remove actor of type 'StLabel' from group of class 'ShellGenericContainer', but the container is not the actor's parent.
length values must specify a unit
[pixel-saver]: Can't find original state for seoras@Iffy: ~ with id 0x3a00006
[pixel-saver]: Can't find original state for seoras@Iffy: ~ with id 0x3e00006
error: Execution of “gnome-tweak-tool” failed:: Command not found

**Comment by lexruee** [comment]
@mackay508 
The problem is that some genius thought it might be a good idea to rename a well known command gnome-tweak-tools to gnome-tweaks. No further comment to that. By the way, Ubuntu 17.10 is not officially released yet...

See here: https://git.gnome.org/browse/gnome-tweak-tool/commit/?id=05600c3af48c70925a2faf5663036f7eef62bff8

**Comment by lestcape** [comment]
@lexruee just an idea and if you use as a workaround ```GLib.find_program_in_path``` ? localized gnome-tweak-tools, if exist launch it if not localized gnome-tweaks and launch it.

**Comment by lexruee** [comment]
@lestcape 
Thanks for the hint. I will look into it. 

I know this can be fixed. But I don't like how upstream handled this "bug report". Allan Day from the GNOME project has stated it perfectly that this change is not beneficial :thinking:.
> This change seems counter-productive to me. The name is well-established and the benefit is minimal at best.

Anyways, I guess we, the extension developers, have to live and accept with some strange decisions from upstream :smile:.

**Comment by LinxGem33** [comment]
@mackay508 

appreciate the feed back, just to make you aware Arc menu does not officially support 17.10 yet as there maybe still packages missing upstream as a result Arc menu may not work.

kind regards

**Comment by mackay508** [comment]
@lexruee Gnome-tweaks launchs the app but Gnome-tweak-tools comes up with command not found.

@LinxGem33 No problem, I know its not the best being on unreleased versions in regards to errors. I'll happily help out where I can.

**Comment by lexruee** [comment]
@mackay508 
You can fill a bug report on https://bugzilla.gnome.org/ and complain that the GNOME devs decided to rename the gnome-tweak-tool command to gnome-tweaks. That is the main reason why you encounter this bug.

In short, it is the fault of the GNOME devs.... They decided to break some GNOME Shell extensions.

**Comment by lestcape** [comment]
@mackay508 I agree with @lexruee but i think this is just a little break, if we compare others gnome shell releases with this. Also gnome shell (gjs), will jump to mozilla core 52 al less with a lot of changes and a lot of new things, that sure will break a lot of another things, All this without take on account the changes that come with shell and not from the changes of gjs. Anyway gnome devs don't considered the gnome tweak as a gnome shell component instead **gnome-shell-extension-prefs** is a component, probably is recommended the usage of this instead of the **gnome-tweak-tool** when is possible.

Anyway, i will just make a ping to the developer @jbicha, because he is a nice people and i think is good that he have user fill-back.

**Comment by jbicha** [comment]
While not as common now, other GNOME apps switched names during GNOME 3 development. One example is `/usr/bin/gnome-disks`

Also changed in GNOME 3.25.4 is that if you want to open the Wi-Fi panel you have to run `gnome-control-center wifi` instead of `gnome-control-center network`.

By the way the .desktop filename didn't change so if you use the .desktop to launch the app, there wouldn't have been a problem this time.

It's not that hard for the gnome-tweak-tool packaging to include a symlink from the old binary name but maybe it's better to just adjust to the new name.

[GNOME 3.26](https://wiki.gnome.org/ThreePointTwentyfive) won't be released for a month and a half.

**Comment by lestcape** [comment]
@jbicha i don't think that will be nice to have an app with a name and a .desktop with another name. Not if they represented the same feature. If they are launched with different parameters in the, desktop file not matter. I think preserved the concordance is more important than preserved the name. Change twice the name one for the application and another for the desktop is more annoying i think.

For this specific case here, i think the failure is a hard-set calls to an externals application without check for the existence first. The name of an application is a decision of the author of the application or in all case of who distributes it. It will be annoying for other that are using it yes, but as it was a decision to use it, is a matter of who decided use it (this is my opinion).

An external application can be installed in different distributions with different names. Also probably they don't exist at all in some distros... To add a button with a link to an specific external application name, will be nice first check for the existence of the application and then add the button. This will prevent bugs in the future. It's not the same a failure than a missing link. The failure is cause by the extension, the missing link is attributable to the an external decisions and can not be considered a bug of the extension itself.

**Comment by jbicha** [comment]
@letscape Thanks for the follow up. There is an issue with migrating favorite-apps for users using desktops besides GNOME that Ubuntu has been struggling with for a while and it's still not solved there yet. Also, maybe we want to switch to the org.gnome style file name for the .desktop. But I'm not going to do any of that this release cycle.

Another place where the old name is kept is the icon name because some icon themes like to customize app icons.

I do apologize for the inconvenience. I've gotten a lot more positive feedback than negative so at this time I don't plan to make any more changes to gnome-tweak-tool naming for 3.26.

**Comment by lexruee** [comment]
@lestcape 

>For this specific case here, i think the failure is hard-set a calls to an externals application without check for the existence first.
> To add a button with a link to an specific external application name, will be nice first check for the existence of the application and then add the button. This will prevent bugs in the future.

You are right and I agree. It's not good solution to assume that GNOME Tweaks/Tweak Tool is installed on a GNOME desktop. So a simple test (guard) to check if the tool is present should be added to menu.js.

> The name of an application is a decision of the author of the application or in all case of who distributes it. 

That is true. But I think it is also the responsibility of the author/distributor to ensure some kind of backwards compatibility. However, in this case renaming a project introduces a goal conflict between backwards compatibility and a consistent naming. You can't have it both ways :-).

@jbicha 
Thanks for joining the discussion :smile:.

>I do apologize for the inconvenience. I've gotten a lot more positive feedback than negative so at this time I don't plan to make any more changes to gnome-tweak-tool naming for 3.26.

No need to apologize :-). We (Arc-Menu) were simply surprised that the binary of the Tweak Tool was renamed too. If I were the author of the Tweak Tool I would simply include a symlink from the old binary name, as you said above. Besides that I would declare `gnome-tweak-tool` as a deprecated command name and in the release of GNOME 3.28 I would remove the symlink.

Anyways, in the end, it's the decision of the GNOME project. Arc-Menu will adapt the name change but we will also keep our extension backwards compatible.

**Comment by lestcape** [comment]
@lexruee "_I think it is also the responsibility of the author/distributor_" I agree. In this specific case i think is a responsibility of distributors/packagers create a symlink, maybe not directly the author, as the application can be installed in different scenarios and the solution could not be the same in all. But i really will not wait for gnome shell devs, they never keep compatibility, just they change all without any advice. This  is not a news so, try to prevent all that you can. I duplicate the shell popup menu "api" and all implementations that i used, because this will ensure that a change there will not break my things... But well, a change directly in gjs will break it and this is what will happens soon... Make an extension is something with a begin, but not with a happy ending (or an ending).

**Comment by jbicha** [comment]
My concern about adding a symlink is how would people know to not use the old name?

I think it makes sense to change the binary name at the same time as the user-visible name. I did mention the binary name change in the [NEWS](https://git.gnome.org/browse/gnome-tweak-tool/tree/NEWS) file.

Hmm, I guess it could be nice to have a 6-month transition time. So if the command stopped working 6 months from now (because the symlink was dropped), you could easily just change the binary because GNOME 3.26 should be somewhat widely used by then. …except this is a GNOME Shell extension and GNOME Software presents all extensions regardless of version to all GNOME 3.22+ users so you still shouldn't break users of older distros. In the end, I guess it wouldn't make much of a difference. And not many people are using the alpha release.

**Comment by lexruee** [comment]
@jbicha 
To let users and developers know that they should use gnome-tweaks instead of the old name, you could add a simple warning message to the Python file gnome-tweaks. 

Something like this: https://github.com/lexruee/gnome-tweak-tool/commit/d20641a7e1c98ad8b0411c07e430db98eef3acd0 [Patch file](https://github.com/LinxGem33/Arc-Menu/files/1181697/0001-gnome-tweaks-Print-a-warning-when-using-the-old-gnom.patch.txt)

**Comment by jbicha** [comment]
@lexruee but who uses gnome-tweak-tool from the command line?

**Comment by lexruee** [comment]
@jbicha 
>@lexruee but who uses gnome-tweak-tool from the command line?

Good question :-). I guess not the average users: https://wiki.ubuntu.com/One%20Hundred%20Papercuts/Average%20users

Maybe I am the only person who uses the tweak tool this way :-). 

So, to come to a final conclusion,  I'll read in the future the NEWS file of GNOME Tweaks and I will complain on GNOME bugzilla :smile:.

**Comment by jbicha** [comment]
@LinxGem33 @lexruee Sorry for the inconvenience, but thank you again for your feedback.

I will be releasing GNOME Tweaks 3.25.90 later today with `/usr/bin/gnome-tweaks` renamed back to `/usr/bin/gnome-tweak-tool`. This fixed [an issue](https://bugzilla.gnome.org/show_bug.cgi?id=785611) with the .desktop tracking in GNOME.

**Comment by lestcape** [comment]
@jbicha like i say, change it in some places and not in another is worse. Change it one time in all places will be better for all point of view. I think is good that you follow a name convention so, don't desist in your intentions.

**Comment by LinxGem33** [comment]
@jbicha 
appreciate you keeping us informed with regards to the recent changes and @lexruee has now back-ported and amended the new changes ready for 3.25 or later also keep up the good work we appreciate your contributions to the Linux community.

kind regards - *Arc menu team*
