### ISSUE TITLE
How To / Bind to <Super>+<Space>

### ISSUE THREAD

**Issue by daniel-wtd** [LinxGem33/Arc-Menu#137]
Hey,

I havent found a way to initiate the start of arc-menu with <Super>+<Space>. Is there any?
Can it be implemented or described in the shortcurt description?

Thanks a lot!

**Comment by lexruee** [comment]
@daniel-wtd 
Fortunately, your `<Super>+<Space>` binding can be realized :-). Just enter `<Super>space` in the textbox as shown in the figure below:
![screenshot from 2017-08-26 20-55-39](https://user-images.githubusercontent.com/649340/29744233-1268d5b8-8aa1-11e7-9e04-46891d54e47a.png)

Please note you also need to change the GNOME keybinding "Switch to next input source" since it already uses the keybinding `<Super>+<Space>`.

@LinxGem33 
In the future I would like to replace this textbox using a simple dialog window :-) that allows users to set a custom menu keybinding in a more intuitive and simple way as shown below:
![screenshot from 2017-08-26 20-58-39](https://user-images.githubusercontent.com/649340/29744251-673e3e70-8aa1-11e7-94c7-dd1d4a224a5d.png)

**Comment by daniel-wtd** [comment]
Sounds awesome and works!

Thanks a lot!

**Comment by LinxGem33** [comment]
@lexruee 
your suggestion sounds perfect ive PM you regarding issue.
