### ISSUE TITLE
Search improvement

### ISSUE THREAD

**Issue by zaplo00** [LinxGem33/Arc-Menu#163]
I wanted to open Caja but it wasn't found when i typed it, so next i tried /usr/bin/caja but it wasn't found either. It would be nice if the menu searched $PATH for possible files. For example Whisker menu in Xfce seem to work (or at least found caja)

**Comment by lexruee** [comment]
@zaplo00 
I'm a little bit confused because [caja](https://github.com/mate-desktop/caja) is the default file browser on the [MATE Desktop](https://mate-desktop.org/) whereas the default file browser on GNOME3 is  [Nautilus](https://wiki.gnome.org/Apps/Nautilus), which is also known as GNOME Files. 

Are you sure you installed caja on your GNOME Desktop?

Anyways, can you please provide more details about your system:
 * Linux distribution & version
 * gnome-shell version
 * Arc-Menu version
 * Do you use multiple desktops on your system?
 * The output of the command: `which caja`
 * The output of the command:  `ls /usr/share/applications | grep caja`

**Comment by LinxGem33** [comment]
closed due to lack of response.
