### ISSUE TITLE
Arc-Menu constantly shows notification to upgrade

### ISSUE THREAD

**Issue by stevedude** [LinxGem33/Arc-Menu#200]
I have a constant notification to update Arc-Menu even though it is the latest version. When I go to https://extensions.gnome.org/, there is no Green icon to update this extension but I always see desktop  notifications to update. Screenshot enclosed.
![arc-menu](https://user-images.githubusercontent.com/8483863/32692952-b215db6c-c6ef-11e7-8918-72616ca99c40.png)

**Comment by lexruee** [comment]
I think this is a problem that only occurs if you installed Arc-Menu from source. Other extensions such as dash-to-panel face the same problem:  https://github.com/jderose9/dash-to-panel/issues/286

So, I think this is a general gnome-shell-extension problem that affects all extensions which are installed from source.

**Comment by LinxGem33** [comment]
also just to add the reason why this happens when you install from source is that extensions.gnome.org,reads the version from the [Metadata.js](https://github.com/LinxGem33/Arc-Menu/blob/master/metadata.json#L8) file and also allocates a version number as the source files are not set extensions.gnome.org will always notify you to update and this will usually happen no matter what extension you use if you install from source.

**Comment by stevedude** [comment]
Thanks for the feedback but all of my extensions were installed via Firefox browser, so there may be something else going on here. However, I'll try deleting all the files and reinstall via the browser again and provide an update.

**Comment by lexruee** [comment]
I think this is a GNOME upstream issue. So for everyone that is interested on fixing this GNOME issue, I would suggest the following links.

* The code that is responsible for the GNOME Shell integration can be found here:
  * https://github.com/GNOME/chrome-gnome-shell
  * https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome

Moreover, the web application that provides the gnome-shell extension web service is called Sweet Tooth:
 * https://wiki.gnome.org/Projects/GnomeShell/SweetTooth
