### ISSUE TITLE
Problems on Ubuntu 17.10

### ISSUE THREAD

**Issue by harcesz** [LinxGem33/Arc-Menu#217]
I've just made a bunch of installs of 17.10, and planned to use arc menu + dash to dock, which worked like a charm for a noob friendly menu solution last time I did it. This time I found out that for some reason;
- arc menus settings screen is to big to fit on the screen, and can't be made smaller
- arc menu doesent have a setting to move it to the bottom of the screen
- they don't magically integrate at all, as they did (might have missed something)

is it just me, or is something wrong?

**Comment by LinxGem33** [comment]
appreciate the feedback, regarding your questions:

> arc menus settings screen is to big to fit on the screen, and can't be made smaller
- the reason is because i left a long message on the extension page regarding a recent bug which reflects on the settings page which has now been removed.

> arc menu doesent have a setting to move it to the bottom of the screen
- it never did.

> they don't magically integrate at all, as they did (might have missed something)
this is for [dash to panel](https://github.com/jderose9/dash-to-panel)
##
please remove the extension and reinstall from gnome extensions website and the large box should be now gone.

kind regards
