### ISSUE TITLE
not working on GTK 3.28

### ISSUE THREAD

**Issue by Gamedev1909** [LinxGem33/Arc-Menu#226]
Hi i compiled and did make enable but after log out and in arc doesnt work still and gnome is hell without this extensions

**Comment by LinxGem33** [comment]
hi thanks for the feed back, ive uploaded the 3.28 version to gnome extensions for review so keep an eye out for that release, just to make you aware that gnome 3.28 isn't officially released till April 26th so the may still be minor packages that the gnome team will update before release.

regarding your issue with installing Arc menu on gnome 3.28 manually ive begun testing in the last few days and i was able to install without issue, the only issue i have come across is the user avatar not showing on the menu but i suspect this will be sorted out closer to gnome 3.28 official release, please see below links on how to install arc menu manually and also the dependencies which are needed.
##
https://github.com/LinxGem33/Arc-Menu/wiki/Installing-from-extensions.gnome.org#manual-installuninstall-using-make

https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies

**Comment by benjaminnyc** [comment]
Hi, I tried your manual install method hoping it would install the one that works on 3.28, but it seems to have installed the older one that does not.

Can you make your 3.28 version (that you submitted to Gnome Shell Extensions) available via Git? Thanks!

**Comment by LinxGem33** [comment]
the link below is directly from gnome extensions website it has been compiled and made ready for distribution for 3.28 this is the version which is waiting review, please make sure you have all dependencies installed including **gnome-menus** 

regarding the git version its up to date when you **Make** install in the terminal it should automatically compile all necessary code i.e schemes, translations etc.
##
https://extensions.gnome.org/review/download/8042.shell-extension.zip

once extracted you need to rename the folder to say `arc-menu@linxgem33.com` then place the folder in `/.local/share/gnome-shell/extensions` and then reboot your system.

**Comment by benjaminnyc** [comment]
Thanks, I guess I was missing gnome-menus, which must be new. Thanks
again, so happy to have this extension back!

B.

-----Original Message-----

Date: Sun, 08 Apr 2018 14:54:38 +0000 (UTC)
Subject: Re: [LinxGem33/Arc-Menu] not working on GTK 3.28 (#226)
Cc: benjaminnyc <benjamin.selzer@gmail.com>, Comment <comment@noreply.g
ithub.com>
To: LinxGem33/Arc-Menu <Arc-Menu@noreply.github.com>
Reply-to: LinxGem33/Arc-Menu <reply+012801325d184e39e2801eaff3a31e76336
a56d82ea171a792cf0000000116e1ef2d92a169ce1290b261@reply.github.com>
From: Andy C <notifications@github.com>
the link below is directly from gnome extensions website it has been
compiled and made ready for distribution for 3.28 this is the version
which is waiting review, please make sure you have all dependencies
installed including gnome-menus

regarding the git version its up to date when you Make install in the
terminal it should automatically compile all necessary code i.e
schemes, translations etc.



https://extensions.gnome.org/review/download/8042.shell-extension.zip

once extracted you need to rename the folder to say arc-menu@linxgem33.
com then place the folder in /.local/share/gnome-shell/extensions and
then reboot your system.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.



  
  





{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c554
93e4bb","name":"GitHub"},"entity":{"external_key":"github/LinxGem33/Arc
-Menu","title":"LinxGem33/Arc-Menu","subtitle":"GitHub
repository","main_image_url":"https://cloud.githubusercontent.com/asset
s/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.c
om/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in GitHub","url":"https://gith
ub.com/LinxGem33/Arc-
Menu"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LinxGem33
in #226: the link below is directly from gnome extensions website it has been compiled and made ready for distribution for 3.28 this is the version which is waiting review, please make sure you have all dependencies installed including **gnome-menus** \r\n\r\nregarding the git version its up to date when you **Make** install in the terminal it should automatically compile all necessary code i.e schemes, translations etc.\r\n##\r\nhttps://extensions.gnome.org/review/download/8042.shell-
extension.zip\r\n\r\nonce extracted you need to rename the folder to
say `arc-menu@linxgem33.com` then place the folder in
`/.local/share/gnome-shell/extensions` and then reboot your
system."}],"action":{"name":"View Issue","url":"https://github.com/Linx
Gem33/Arc-Menu/issues/226#issuecomment-379556474"}}}

**Comment by benjaminnyc** [comment]
Do I need to keep the Arc-Menu folder in my Home directory? When the extension is installed via Gnome Shell Extensions, where does that folder reside? Can I put it there?

Also, will I get updates from Gnome Shell Extensions since I've manually installed it?

**Comment by edrose** [comment]
I'm also having issues with Gnome 3.28. LookingGlass gives the error as 

  Requiring GMenu, version none: Typelib file for namespace 'GMenu' (any version) not found

**Comment by LinxGem33** [comment]
hi appreciate the feedback

> please make sure you have all dependencies installed including gnome-menus

as you can see above from my previous comment to another user i also had trouble installing Arc menu on gnome 3.28 as the packaged `gnome-menus` needed to be installed i don't know if this was a new package or just something i overlooked, but most of the application menu extensions now need this package, that's one of the negatives and also positive things about open source and developing for (gnome) is things are always changing at a rapid pace.

**Comment by LinxGem33** [comment]
closing as issue is resolved.
