### ISSUE TITLE
Menu don't display with bottom panel

### ISSUE THREAD

**Issue by Philippe734** [LinxGem33/Arc-Menu#231]
Ubuntu 18.04
With the extension dash to panel to move panel at bottom, the arc menu don't showed up when clicked. If panel at top, arc menu works fine.

**Comment by LinxGem33** [comment]
I've just tested now on a ubuntu 18.04 test machine and its working fine make sure you have the `gnome-menus` package installed.
```
sudo apt install gnome-menus
```
kind regards

**Comment by Philippe734** [comment]
Please watch the screen recorded below, you will see the issue. Panel on top : OK. Panel at bottom : NOK. When panel at botton, when I click the menu, we can see a red line appears at the bottom of the menu and the menu don't show up.
https://www.dropbox.com/s/obtruu78nqukcj4/Issue%23231-Record-2018-05-16%2020%3A29%3A55.mp4?dl=0

**Comment by Philippe734** [comment]
I confirm gnome menus is installed:
```
:~$ apt policy gnome-menus
gnome-menus:
  Installé : 3.13.3-11ubuntu1
  Candidat : 3.13.3-11ubuntu1
 Table de version :
 *** 3.13.3-11ubuntu1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by LinxGem33** [comment]
Before logging your bug report please make sure that you first have these packages installed as Arc menu depends on them and that you don't have custom corners installed: please see this issue for further details #194 .

```
sudo apt install gir1.2-gmenu-3.0
```
**Edit:**
Overall, i feel this may be just a Ubuntu problem as the Ubuntu people decided to ship a broken or incomplete GNOME Desktop environment with Ubuntu 18.04.
In short, this can be fixed by installing the following dependencies, which are usually installed per default on any sane GNOME-based Linux distribution however ill take a look at your logs and see if i can replicate your issue.
##
**Bug report**

appreciate the feedback, could you give us  **Full Logs from the systemd journal**:
```
journalctl /usr/bin/gnome-shell -f -o cat
```
For the information we need please see:
[Supporting Information](https://github.com/LinxGem33/Arc-Menu/wiki/Supporting-Information)

also if you can make sure you have all the dependencies installed:
[Gnome Dependencies](https://github.com/LinxGem33/Arc-Menu/wiki/Supported-Distributions#gnome-dependencies)

kind regards

**Comment by Philippe734** [comment]
gir1.2-gmenu-3.0 is already installed.
I installed all the dependencies for Gnome, reboot, but same issue.
Please see the video in the comment #3.

Here log from systemd journal:
```
:~$ journalctl /usr/bin/gnome-shell -f -o cat
WARNING: addSignalMethods is replacing existing [0x5586919a8640 Gjs_ShowAppsIcon.dash-item-container] connect method
WARNING: addSignalMethods is replacing existing [0x5586919a8640 Gjs_ShowAppsIcon.dash-item-container] disconnect method
WARNING: addSignalMethods is replacing existing [0x5586919a8640 Gjs_ShowAppsIcon.dash-item-container] emit method
Some code accessed the property 'SHELL_KEYBINDINGS_SCHEMA' on the module 'windowManager'. That property was defined with 'let' or 'const' inside the module. This was previously supported, but is not correct according to the ES6 standard. Any symbols to be exported from a module must be defined with 'var'. The property access will work as previously for the time being, but please fix your code anyway.
JS WARNING: [/usr/share/gnome-shell/extensions/ubuntu-dock@ubuntu.com/appIcons.js 1027]: unreachable code after return statement
JS ERROR: ReferenceError: GLib is not defined
enable/extensionChangedHandler</<@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:64:17

JS ERROR: ReferenceError: GLib is not defined
enable/extensionChangedHandler</<@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:64:17

JS ERROR: ReferenceError: GLib is not defined
enable/extensionChangedHandler</<@/home/user/.local/share/gnome-shell/extensions/dash-to-panel@jderose9.github.com/extension.js:64:17

Error looking up permission: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.impl.portal.PermissionStore was not provided by any .service files
GNOME Shell started at Thu May 17 2018 13:58:48 GMT+0200 (CEST)
```

**Comment by Philippe734** [comment]
My apologize! It's not a issue from Arc-Menu! The menu didn't showed up when panel at bottom, because... the height of my virtual machine was to small! If I increase the height of the window of my virtual machine, then the arc-menu works fine when panel at bottom. Sorry, it's my fault. But, it's good to know now.

**Comment by LinxGem33** [comment]
no problem and i appreciate you letting me know and I'm glad you managed to find the issue, sometimes it turns out to be the simplest thing but as you say this will help other users to identify this same issue.

kind regards

**Comment by LinxGem33** [comment]
closed due to being resolved by user.

**Comment by zagortenay333** [comment]
FYI it's a bug in dash-to-panel: https://github.com/home-sweet-gnome/dash-to-panel/issues/200
