### ISSUE TITLE
Arc Menu causes Gnome Shell to crash when installing/updating packages

### ISSUE THREAD

**Issue by thomasstevenson** [LinxGem33/Arc-Menu#34]
I've noticed that when I have Arc Menu enabled and I am installing/updating packages on my system, Gnome Shell often crashes.

On my native install of Ubuntu Gnome, this crash hides all Gnome Shell widgets (eg. panel and window decorations) & freezes my computer for around 5-10 seconds, before automatically re-loading Gnome Shell back to normal.

When trying Ubuntu Gnome in VirtualBox, the crash didn't automatically re-load Gnome Shell and caused my system to have no window manager running it (no window decorations, black background under windows and unable to type). As well, when running `gnome-shell --replace` in a Terminal, the crash adds the following line to the Terminal output text:
`Segmentation fault (core dumped)`

The most predictable way to reproduce this issue is to download and install Ubuntu Gnome (I mainly use 16.04, but the crash also happens in 17.04), enable Arc Menu and install the software updates. The crash nearly always happens during the installation of the updates.

**Comment by thomasstevenson** [comment]
I have also tested to find out that this issue isn't specific to Arc Menu. The crash happens in the same way when the built-in Gnome Shell Apps Menu extension (by gcampax) is enabled.

The crash even occurs when I leave the software updates running with only the stock app grid showing (by pressing Super + A) and without any extensions enabled.

Perhaps this is a bug with a built-in component of Gnome Shell which happens to be used by Arc Menu? I wonder if it's possible to create a workaround for this issue in Arc Menu.

**Comment by LinxGem33** [comment]
@thomasstevenson 

appreciate the feed back, as your maybe aware a segmentation fault is the result of a memory access violation. The program has referred to a memory address outside of what was allocated to it, and the OS kernel responds by killing the program with SIGSEGV.

this could be a mistake, since there is no point in trying to access inaccessible memory (it cannot be done). mistakes of this sort are easy to make, however, particularly in languages such as C and C++ and JavaScript . 

It indicates a bug in either the program itself possible pointer in the code being directed wrongly or a library it links to in this case i suspect it being a issue in gnome shell as arc menu has just passed a code review please see #33 for some of the report. If you wish to report the bug  it is a good idea to include a backtrace of the events that led up to the seg fault.

kind regards

**Comment by LinxGem33** [comment]
could everybody now test by manually installing from the main branch as i believe the fix has been found for the issue following testing.

kind regards

**Comment by LinxGem33** [comment]
closing due to lack of response.
