### ISSUE TITLE
Power/lock/logout overflow with the Arc-Dark shell theme

### ISSUE THREAD

**Issue by Tiamarth** [LinxGem33/Arc-Menu#6]
Screenshot, http://i.imgur.com/1VGVtTf.png

**Comment by LinxGem33** [comment]
@Tiamarth 

appreciate the feed back, the issue is not with arc menu but rather a css styling issue with the arc theme, what you need to do is change the font size by editing this [Line](https://github.com/LinxGem33/OSX-Arc-White/blob/master/gnome-shell/gnome-shell.css#L11) in the gnome-shell > gnome-shell.css and changing the font size to 10.5pt most other themes will work correctly however the arc theme uses a smaller size to the standard size hence why you get the over flow issue.

kind regards

**Comment by BatchHeader** [comment]
I am using the System76 Pop theme and confirm the same issue.

Which selector should be be changing the font size? I have tried "stage" but no effect

**Comment by LinxGem33** [comment]
@BatchHeader 

appreciate the feed back, Ive tested the system 76 Pop theme and i cant replicate your issue it seems to be working fine.

** System76 Pop theme**
![pop](https://cloud.githubusercontent.com/assets/19158615/26361554/45af7ecc-3fd3-11e7-9134-b906dd6d5e31.png)

kind regards

**Comment by BatchHeader** [comment]
@LinxGem33 Seeing your screenshot realised I had gtk theme active but not shell theme. Done that, now all sorted. :+1:

**Comment by JasonLG1979** [comment]
@LinxGem33 the problem is 2 fold.

1. You're using pixels as the width for the 'main-box' when you should be using em's so it's defendant on font size.

2. you're adding a bunch of stuff to this.menu and not calling this.menu.actor.set_width(-1); so the menu will auto set the right width.

Do those 2 things and the bug disappears.

**Comment by LinxGem33** [comment]
@JasonLG1979 

appreciate the feed back, I’ve been slowly learning JavaScript over the past month and a half as JavaScript is not my native programming language so i really do appreciate you pointing out where i could improve, would it be possible for you to send a pull request with the changes you mentioned so i can integrate them into the main branch.

kind regards

**Comment by LinxGem33** [comment]
@JasonLG1979 

really appreciate you taking the time to contribute, would it be ok to credit you as a contributor?

looking at the code it looks good i know what you mean now after viewing the code.

kind regards
