### ISSUE TITLE
Wiki now implemented 

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#71]
@lexruee 

just a quick update, i have now set-up the wiki and its corresponding pages so we can both edit it over time with new information. :smile: 

please see [wiki](https://github.com/LinxGem33/Arc-Menu/wiki)

**Comment by LinxGem33** [comment]
@lexruee 

also Arc menu passed the remaining code reviews and is now at version 13 :smile:

**Comment by lexruee** [comment]
@LinxGem33 
Nice! I need to become a GNOME developer so that our future releases are processed more quickly :smile: on extensions.gnome.org.

_Offtopic - readme.md:_
Can you add a "step 5" in section "Manual Installation"?
Unfortunately, it is always required to restart the GNOME Shell to reload an extension :cry:  ...

With the following extra line our Manual Installation is rock solid again :smile::

> 5. Logout  from the current GNOME session and login again for the changes to take effect. Alternatively, you can restart the GNOME Shell with Alt + F2 and enter 'r' (without quotes).

**Comment by LinxGem33** [comment]
@lexruee 

i know what you mean it takes so long to process :confused: i will update the README asap.

also i will just make a minor re-code for the about page as the GNU licence is not showing at the bottom of the about page.

**Comment by lexruee** [comment]
@LinxGem33 
Thanks :smile:.

Regarding the about page: Sorry for that :scream:. I think I omitted a line of code when I solved a merge conflict with git-meld :thinking:.

**Comment by LinxGem33** [comment]
@lexruee 

it happens :smile: 

ill hopefully push the changes later, at the moment I’m just reviewing all the code for Arc menu as there has been heavy development over past week so I’m just looking were everything go's in preparation for adding some more features and also to follow your work flow so we don’t have code conflicts :laughing: and also we keep the code consistent.
