### ISSUE TITLE
Symbolic icon solution for theme wide integration

### ISSUE THREAD

**Issue by LinxGem33** [LinxGem33/Arc-Menu#88]
all discussions can be made here regarding this issue :smile:

**Comment by lexruee** [comment]
**@LinxGem33** 

I made a pull request https://github.com/LinxGem33/Arc-Menu/pull/89 which fixes an issue of the pull request https://github.com/LinxGem33/Arc-Menu/pull/87 from @itmitica. I think this issue is now fixed. However, I don't like the adapta-fix as it should be fixed upstream :-). Let me know what you think and if we should merge it.

Here are some screenshots:
**Without the refinement of the adapta-fix:**
![adapta-fix-issue](https://user-images.githubusercontent.com/649340/28247927-0e32f342-6a3b-11e7-895d-4f25885bbca7.png)

**With the refinement of the adapta-fix:**
![adapta-fix](https://user-images.githubusercontent.com/649340/28247918-ee853bb8-6a3a-11e7-99f2-0370578b1522.png)

**Comment by LinxGem33** [comment]
@lexruee 

i think i might have a possible solution please test my flat adapta osx theme which i sent you and let me know if this issue exists using that theme before i merge the pull request.

**Comment by lexruee** [comment]
here are some screenshots of the flat adapta osx theme when i use the pull request https://github.com/LinxGem33/Arc-Menu/pull/89:

**flat adapta osx theme - arc menu icon**
![screenshot from 2017-07-16 16-22-49](https://user-images.githubusercontent.com/649340/28248324-45ccd310-6a43-11e7-8b11-386674d95e97.png)

**flat adapta osx theme - system icon**
![screenshot from 2017-07-16 16-23-17](https://user-images.githubusercontent.com/649340/28248325-472f7028-6a43-11e7-88ca-64e11df04ed9.png)

**Comment by LinxGem33** [comment]
testing complete issue closed ref: #89
